[package]
name = "ds-algo"
version = "0.1.0"
authors = ["Pradeep S <75474807+iamprady@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
